import {
  Finding,
  ModuleName,
  Severity,
  FindingCategory,
  FindingType,
  EvidenceType,
  EvidenceSource,
  ExternalBenchmark,
} from '@convertaudit/contracts';

export interface FindingTemplateDefinition {
  id: number;
  code: string;
  module: ModuleName;
  category?: FindingCategory;
  findingType?: FindingType;
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  severityNum: Severity;
  effort: 1 | 2 | 3;
  impactWeight: number; // 0.5 to 1.5
  conversionRelevance?: number; // 0.5 to 1.5 (§6)
  evidenceType?: EvidenceType;
  source?: EvidenceSource;
  heuristic?: string;
  benchmark?: ExternalBenchmark;
  render: (params: Record<string, any>) => {
    headline: string;
    impact: string;
    fix: string;
    developer_brief: string;
    observed?: Record<string, any> | string;
    inference?: string;
    assumptions?: string[];
  };
}

export const FINDING_CATALOG: Record<string, FindingTemplateDefinition> = {
  // Speed (1xx)
  SPEED_LCP_SLOW: {
    id: 101,
    code: 'SPEED_LCP_SLOW',
    module: 'speed',
    category: 'speed',
    findingType: 'TECHNICAL',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 2,
    impactWeight: 1.3,
    conversionRelevance: 1.1,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Core Web Vitals recommend Largest Contentful Paint ≤ 2.5 seconds on mobile emulation for a smooth first impression.',
    benchmark: {
      claim: '53% of mobile visits are abandoned if pages take longer than 3 seconds to load',
      source: 'Google / SOASTA Research',
      date: '2017',
      context: 'Mobile retail and content web pages under simulated 3G/4G connections',
    },
    render: (p) => ({
      headline: `Your phone visitors wait ${(p.lcp_ms ? (p.lcp_ms / 1000).toFixed(1) : '4.5')} seconds before seeing your main content.`,
      impact: 'Delayed visual loading increases bounce risk as mobile users encounter an empty or incomplete screen.',
      fix: 'Optimize the hero image, preload key fonts, and eliminate render-blocking CSS/JS.',
      developer_brief: `Task: Optimize Largest Contentful Paint (LCP)\nTarget: Reduce LCP to ≤ 2.5s on mobile emulation.\nTarget Element: ${p.element_selector || 'hero banner'}\nAction: Add fetchpriority="high", inline critical CSS, ensure proper aspect-ratio sizing.`,
      observed: p.lcp_ms ? `LCP measured at ${p.lcp_ms}ms on mobile viewport (target ≤ 2500ms). Target element: ${p.element_selector || 'body'}` : undefined,
    }),
  },
  SPEED_HEAVY_IMAGE: {
    id: 102,
    code: 'SPEED_HEAVY_IMAGE',
    module: 'speed',
    category: 'speed',
    findingType: 'TECHNICAL',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.4,
    conversionRelevance: 1.0,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Mobile network connections are sensitive to total asset payload. Keeping hero images under 150 KB minimizes transmission delays.',
    render: (p) => {
      const mb = p.bytes ? (p.bytes / (1024 * 1024)).toFixed(1) : '3.8';
      return {
        headline: `Your main homepage image is ${mb} MB — phones waste seconds downloading it.`,
        impact: 'Oversized images consume cellular bandwidth and delay initial rendering on mobile devices.',
        fix: 'Compress the image and convert it to modern WebP or AVIF format under 150 KB.',
        developer_brief: `Task: Compress & resize hero image\nTarget: ≤ 150 KB WebP/AVIF format.\nCurrent size: ${mb} MB. Rendered width: ${p.rendered_w || 390}px, Natural width: ${p.natural_w || 3000}px.\nAction: Generate responsive srcset and use modern image compression.`,
        observed: {
          fileSizeMB: parseFloat(mb),
          renderedWidth: p.rendered_w || 390,
          naturalWidth: p.natural_w || 3000,
          selector: p.selector || 'img',
        },
      };
    },
  },
  SPEED_IMAGE_FORMAT: {
    id: 103,
    code: 'SPEED_IMAGE_FORMAT',
    module: 'speed',
    category: 'speed',
    findingType: 'TECHNICAL',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 1,
    impactWeight: 0.9,
    conversionRelevance: 0.8,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Serving images in WebP or AVIF format provides superior compression compared to legacy PNG or JPEG without visible quality loss.',
    render: (p) => ({
      headline: 'Images are served in legacy formats instead of modern WebP or AVIF.',
      impact: 'Legacy formats (JPEG/PNG) produce larger file sizes than modern WebP or AVIF, increasing data transfer.',
      fix: 'Serve images in modern WebP or AVIF formats for smaller file sizes without quality loss.',
      developer_brief: `Task: Serve next-gen image formats\nTarget: WebP or AVIF format for all images.\nEstimated bandwidth savings: ${p.est_saving_bytes ? Math.round(p.est_saving_bytes / 1024) : '350'} KB.`,
      observed: p.est_saving_bytes ? `Estimated potential savings: ${Math.round(p.est_saving_bytes / 1024)} KB` : 'Legacy image formats detected in network requests',
    }),
  },
  SPEED_RENDER_BLOCKING: {
    id: 106,
    code: 'SPEED_RENDER_BLOCKING',
    module: 'speed',
    category: 'speed',
    findingType: 'TECHNICAL',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 2,
    impactWeight: 1.2,
    conversionRelevance: 1.0,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Deferring non-critical scripts and inlining critical CSS allows the browser to paint above-the-fold content immediately.',
    render: (p) => ({
      headline: 'Scripts and styles stop your page from showing anything to visitors right away.',
      impact: 'Render-blocking assets delay the first content paint by forcing the browser to wait before displaying content.',
      fix: 'Defer non-critical JavaScript and inline critical above-the-fold CSS.',
      developer_brief: `Task: Eliminate render-blocking resources\nAction: Add 'defer' or 'async' to external script tags. Split CSS into critical and non-critical.`,
      observed: p.blocking_count ? `${p.blocking_count} render-blocking stylesheets or synchronous scripts identified` : 'Synchronous scripts/stylesheets blocking early rendering',
    }),
  },
  SPEED_TTFB_SLOW: {
    id: 109,
    code: 'SPEED_TTFB_SLOW',
    module: 'speed',
    category: 'speed',
    findingType: 'TECHNICAL',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 3,
    impactWeight: 1.1,
    conversionRelevance: 0.9,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Time to First Byte under 800 ms ensures mobile browsers can begin parsing HTML and fetching sub-resources promptly.',
    render: (p) => ({
      headline: `Your web server takes ${p.ttfb_ms || 950} ms to respond before sending any data.`,
      impact: 'High Time to First Byte delays every subsequent resource from loading.',
      fix: 'Implement page caching or deploy a Content Delivery Network (CDN) like Cloudflare.',
      developer_brief: `Task: Improve Server Response Time (TTFB)\nTarget: TTFB ≤ 800 ms.\nCurrent: ${p.ttfb_ms || 950} ms.\nAction: Enable page caching, optimize database queries, or route through a global edge CDN.`,
      observed: `Server response time measured at ${p.ttfb_ms || 950}ms (target ≤ 800ms).`,
    }),
  },
  SPEED_CLS_HIGH: {
    id: 112,
    code: 'SPEED_CLS_HIGH',
    module: 'speed',
    category: 'ux',
    findingType: 'UX',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 2,
    impactWeight: 0.9,
    conversionRelevance: 0.9,
    evidenceType: 'performance',
    source: 'BROWSER',
    heuristic: 'Core Web Vitals recommend maintaining CLS ≤ 0.10 by explicitly setting aspect ratio or dimensions on media.',
    render: (p) => ({
      headline: 'Page content jumps around while loading, causing visitors to mis-click.',
      impact: 'Layout shifts cause visual instability and unintended taps when elements move unexpectedly.',
      fix: 'Always specify explicit width and height dimensions on all images, banners, and embeds.',
      developer_brief: `Task: Eliminate Cumulative Layout Shift (CLS)\nTarget: CLS ≤ 0.10.\nAction: Add width and height attributes to <img> and <iframe> tags to reserve layout space.`,
      observed: p.cls ? `Cumulative Layout Shift measured at ${p.cls} (threshold ≤ 0.10)` : 'Layout shifts detected during page load',
    }),
  },

  // Clarity (2xx)
  CLARITY_HEADLINE_VAGUE: {
    id: 201,
    code: 'CLARITY_HEADLINE_VAGUE',
    module: 'clarity',
    category: 'clarity',
    findingType: 'CLARITY',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.4,
    conversionRelevance: 1.3,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'Hero headlines that explicitly state the core service, target audience, and primary benefit establish immediate visitor orientation.',
    render: (p) => ({
      headline: 'Your headline does not tell a first-time visitor what service or product you offer.',
      impact: 'When visitors cannot immediately confirm what a website offers, they face uncertainty and are more likely to return to search results.',
      fix: 'Replace generic phrases ("Welcome", "Your success") with a clear statement of your offering and location.',
      developer_brief: `Task: Rewrite hero headline\nCurrent: "${p.current_headline || 'Welcome to our site'}"\nSuggested Pattern: [Core Service] in [Location] — [Key Benefit/Speed Guarantee].`,
      observed: {
        currentHeadline: p.current_headline || 'Generic or missing headline',
        serviceKeywordsFound: p.service_found ?? false,
        locationFound: p.location_found ?? false,
      },
    }),
  },
  CLARITY_NO_VALUE_PROP: {
    id: 202,
    code: 'CLARITY_NO_VALUE_PROP',
    module: 'clarity',
    category: 'clarity',
    findingType: 'CLARITY',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.2,
    conversionRelevance: 1.2,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'A clear 1-2 sentence supporting description directly under the H1 communicates key differentiators (e.g., speed, quality, warranty).',
    render: (p) => ({
      headline: 'Your hero section lacks a clear value proposition explaining why customers should choose you.',
      impact: 'Without an immediate benefit or differentiator, prospective customers cannot evaluate why your offering fits their specific needs.',
      fix: 'Add a 1-2 sentence supporting description directly below your main headline.',
      developer_brief: `Task: Add hero value proposition sub-headline\nAction: Insert a supporting <p> element (16-18px) directly under <h1> stating the customer benefit.`,
      observed: p.observed || 'No supporting paragraph text detected within hero section',
    }),
  },
  CLARITY_NEXT_STEP_UNCLEAR: {
    id: 204,
    code: 'CLARITY_NEXT_STEP_UNCLEAR',
    module: 'clarity',
    category: 'clarity',
    findingType: 'CLARITY',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.3,
    conversionRelevance: 1.3,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'An action-oriented primary button placed directly after value messaging provides a frictionless forward path.',
    render: () => ({
      headline: 'Visitors who are interested cannot immediately see what action to take next.',
      impact: 'Missing next-step guidance stalls motivated buyers and creates friction in the discovery flow.',
      fix: 'Place a high-contrast button ("Get a Free Quote", "Book Online") right after the headline.',
      developer_brief: `Task: Add clear primary call-to-action in hero\nAction: Position a primary button element directly below hero text with verb-led copy.`,
      observed: 'No high-contrast action button adjacent to hero text',
    }),
  },
  CLARITY_LOW_CONTRAST_HEADLINE: {
    id: 208,
    code: 'CLARITY_LOW_CONTRAST_HEADLINE',
    module: 'clarity',
    category: 'ux',
    findingType: 'UX',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 1,
    impactWeight: 0.8,
    conversionRelevance: 0.8,
    evidenceType: 'visual',
    source: 'BROWSER',
    heuristic: 'WCAG AA standards recommend a minimum contrast ratio of 4.5:1 for normal text and 3:1 for large text against background imagery.',
    render: (p) => ({
      headline: 'Your headline text blends into the background image and is difficult to read.',
      impact: 'Insufficient text contrast creates eye strain and reduces legibility, particularly in outdoor mobile lighting.',
      fix: 'Add a dark overlay or text shadow to guarantee a minimum 4.5:1 contrast ratio.',
      developer_brief: `Task: Improve headline text contrast\nAction: Add a background overlay (e.g., rgba(0,0,0,0.5)) or adjust text color to achieve WCAG AA contrast.`,
      observed: p.contrastRatio ? `Measured contrast ratio: ${p.contrastRatio}:1 (minimum required: 4.5:1)` : 'Low text-to-background contrast detected',
    }),
  },

  // Conversion (3xx)
  CONV_NO_PRIMARY_CTA: {
    id: 301,
    code: 'CONV_NO_PRIMARY_CTA',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'critical',
    severityNum: Severity.CRITICAL,
    effort: 1,
    impactWeight: 1.5,
    conversionRelevance: 1.5,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'A clear, primary call-to-action in the hero section guides motivated visitors directly to inquiry or purchase.',
    render: (p) => ({
      headline: 'There is no obvious button or call-to-action for visitors to become a lead.',
      impact: 'Without an immediate and visible call-to-action, visitors face uncertainty about how to proceed and are more likely to leave without converting.',
      fix: 'Add a prominent primary action button ("Get a Quote", "Book an Appointment") in your hero.',
      developer_brief: `Task: Implement primary CTA button\nLocation: Above the fold (< 844px mobile height).\nAction: Create a prominent button with ≥ 48px height, high-contrast background, and actionable copy.`,
      observed: p.observed || 'No interactive element meeting CTA prominence threshold detected above the mobile fold',
    }),
  },
  CONV_NO_TEL_LINK: {
    id: 306,
    code: 'CONV_NO_TEL_LINK',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.3,
    conversionRelevance: 1.4,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Wrapping phone numbers in tel: links enables native one-tap calling on all mobile devices.',
    render: (p) => ({
      headline: 'Mobile visitors cannot tap your phone number to call you immediately.',
      impact: 'Unlinked phone numbers require mobile visitors to manually copy or memorize the digits, introducing friction for phone leads.',
      fix: 'Wrap your phone number in an `<a href="tel:...">` link.',
      developer_brief: `Task: Make phone number clickable\nAction: Change <p>555-123-4567</p> to <a href="tel:+15551234567" class="btn-phone">Call (555) 123-4567</a>.`,
      observed: p.observed || (p.phoneNumber ? `Phone number "${p.phoneNumber}" detected as plain text with no tel: href` : 'Phone number rendered without clickable tel: link'),
    }),
  },
  CONV_PHONE_NOT_LINKED: {
    id: 307,
    code: 'CONV_PHONE_NOT_LINKED',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 1,
    impactWeight: 1.0,
    conversionRelevance: 1.2,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Wrapping detected phone numbers in tel: hyperlinks enables direct mobile calling.',
    render: (p) => ({
      headline: `The phone number "${p.phone_text || ''}" appears as plain text instead of a tap-to-call link.`,
      impact: 'Visitors on smartphones must copy-paste or switch apps to dial, creating avoidable friction.',
      fix: 'Wrap the phone text in an HTML `tel:` hyperlink.',
      developer_brief: `Task: Convert plain text phone to tel: link\nAction: Wrap text matching "${p.phone_text || 'phone'}" with <a href="tel:...">.`,
      observed: {
        phoneNumber: p.phone_text || '',
        clickable: false,
        href: null,
        selector: p.selector || 'p',
      },
    }),
  },
  CONV_CTA_BELOW_FOLD: {
    id: 302,
    code: 'CONV_CTA_BELOW_FOLD',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.2,
    conversionRelevance: 1.4,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Placing the primary CTA within the initial viewport (≤844px) ensures it is immediately visible upon landing without requiring scroll interaction.',
    render: (p) => {
      const topEdge = p.topEdgePx || p.elementTop || 927;
      const vpHeight = p.viewportHeight || 844;
      const belowPx = Math.max(1, topEdge - vpHeight);
      return {
        headline: `CTA begins ${belowPx}px below the first mobile viewport.`,
        impact: 'Placing the primary action below the first screen requires visitors to scroll before understanding what action to take, introducing friction on mobile.',
        fix: 'Move your primary call-to-action button into the first viewport (≤ 844px).',
        developer_brief: `Task: Move primary CTA above the fold\nTarget: Top edge of CTA must be ≤ ${vpHeight}px on mobile viewports (currently at ${topEdge}px).\nAction: Reposition element ${p.elementSelector || '.btn-primary'} higher in DOM or adjust hero padding.`,
        observed: {
          viewportWidth: p.viewportWidth || 390,
          viewportHeight: vpHeight,
          elementSelector: p.elementSelector || '.btn-primary',
          elementTop: topEdge,
          aboveFold: false,
          pixelsBelowFold: belowPx,
        },
      };
    },
  },
  CONV_FORM_TOO_LONG: {
    id: 309,
    code: 'CONV_FORM_TOO_LONG',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 1,
    impactWeight: 1.0,
    conversionRelevance: 1.2,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Forms requesting non-essential qualification details upfront create cognitive friction on mobile keypads. Testing a shorter initial form often improves completion rates.',
    render: (p) => ({
      headline: `Your lead form has ${p.field_count || 'several'} fields, which may introduce input friction.`,
      impact: 'Forms with numerous qualification fields create input fatigue on mobile touchscreens.',
      fix: 'Reduce your initial form to essential lead fields (e.g. Name, Phone, and Email), deferring secondary questions to follow-up.',
      developer_brief: `Task: Streamline lead capture form\nAction: Keep essential contact fields in step 1. Move secondary qualification fields (${(p.fields || []).slice(3).join(', ') || 'additional fields'}) to step 2 or follow-up.`,
      observed: {
        fieldCount: p.field_count || 0,
        fields: p.fields || [],
        requiredCount: p.required_count,
        hasCaptcha: p.has_captcha,
      },
    }),
  },
  CONV_TAP_TARGET_SMALL: {
    id: 312,
    code: 'CONV_TAP_TARGET_SMALL',
    module: 'conversion',
    category: 'ux',
    findingType: 'UX',
    severity: 'medium',
    severityNum: Severity.MEDIUM,
    effort: 1,
    impactWeight: 1.1,
    conversionRelevance: 1.1,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Mobile accessibility and conversion guidelines (WCAG 2.5.5) recommend touch targets of at least 44x44 CSS pixels (recommended 48x48px).',
    render: (p) => ({
      headline: 'Interactive buttons or links are smaller than 44x44px, causing accidental taps.',
      impact: 'Small tap targets frustrate mobile visitors and lead to mistaps on touchscreen devices.',
      fix: 'Increase button padding or container size to at least 48x48px on mobile.',
      developer_brief: `Task: Increase tap target size\nCurrent dimensions: ${p.width || 36}x${p.height || 36}px. Target: minimum 44x44px (recommended 48x48px). Selector: ${p.selector || 'button'}.`,
      observed: {
        width: p.width || 36,
        height: p.height || 36,
        selector: p.selector || 'button',
        targetMinimum: '44x44px',
      },
    }),
  },
  CONV_NO_TRUST_NEAR_CTA: {
    id: 315,
    code: 'CONV_NO_TRUST_NEAR_CTA',
    module: 'conversion',
    category: 'trust',
    findingType: 'TRUST',
    severity: 'low',
    severityNum: Severity.LOW,
    effort: 1,
    impactWeight: 0.9,
    conversionRelevance: 1.0,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'If the business has verified review ratings, certifications, or guarantees, displaying them adjacent to the primary CTA helps alleviate user hesitation.',
    render: (p) => ({
      headline: 'No verified trust badges, reviews, or guarantees detected near your primary call-to-action.',
      impact: 'Visitors may feel hesitation at the point of conversion without visible proof of credibility.',
      fix: 'If your business has verified reviews or guarantees, place a rating or badge directly beneath the CTA.',
      developer_brief: `Task: Add verifiable trust signals adjacent to primary CTA\nAction: If verified customer ratings or credentials exist, place review summary (e.g. rating + review count) or guarantee microcopy directly below the primary button. Do not invent fake reviews.`,
      observed: p.observed || 'No verified trust elements (ratings, reviews, guarantees, accreditations) found within 300px of primary CTA',
    }),
  },
  CONV_TRUST_SIGNALS_MISSING: {
    id: 315,
    code: 'CONV_TRUST_SIGNALS_MISSING',
    module: 'conversion',
    category: 'trust',
    findingType: 'TRUST',
    severity: 'low',
    severityNum: Severity.LOW,
    effort: 1,
    impactWeight: 0.9,
    conversionRelevance: 1.0,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'If the business has verified review ratings, certifications, or guarantees, displaying them adjacent to the primary CTA helps alleviate user hesitation.',
    render: (p) => ({
      headline: 'No verified trust badges, reviews, or guarantees detected near your primary call-to-action.',
      impact: 'Visitors may feel hesitation at the point of conversion without visible proof of credibility.',
      fix: 'If your business has verified reviews or guarantees, place a rating or badge directly beneath the CTA.',
      developer_brief: `Task: Add verifiable trust signals adjacent to primary CTA\nAction: If verified customer ratings or credentials exist, place review summary (e.g. rating + review count) or guarantee microcopy directly below the primary button. Do not invent fake reviews.`,
      observed: p.observed || 'No verified trust signals detected in the initial viewport',
    }),
  },
  CLARITY_VALUE_PROP_MISSING: {
    id: 202,
    code: 'CLARITY_VALUE_PROP_MISSING',
    module: 'clarity',
    category: 'clarity',
    findingType: 'CLARITY',
    severity: 'high',
    severityNum: Severity.HIGH,
    effort: 1,
    impactWeight: 1.2,
    conversionRelevance: 1.2,
    evidenceType: 'dom',
    source: 'DETERMINISTIC_RULE',
    heuristic: 'A clear supporting description directly under the H1 communicates key differentiators (e.g., speed, quality, warranty).',
    render: (p) => ({
      headline: 'Your hero section lacks a clear value proposition explaining why customers should choose you.',
      impact: 'Without an immediate benefit or differentiator, visitors cannot quickly determine if this service fits their needs.',
      fix: 'Add a 1-2 sentence supporting description directly below your main headline.',
      developer_brief: `Task: Add hero value proposition sub-headline\nAction: Insert a supporting <p> element (16-18px) directly under <h1> stating the customer benefit.`,
      observed: p.observed || 'Hero section contains heading without supporting value proposition text',
    }),
  },
  CONV_NO_CONTACT_METHOD: {
    id: 316,
    code: 'CONV_NO_CONTACT_METHOD',
    module: 'conversion',
    category: 'conversion',
    findingType: 'CONVERSION',
    severity: 'critical',
    severityNum: Severity.CRITICAL,
    effort: 1,
    impactWeight: 1.5,
    conversionRelevance: 1.5,
    evidenceType: 'dom',
    source: 'BROWSER',
    heuristic: 'Every business landing page requires at least one prominent direct contact mechanism (tap-to-call, email, or form).',
    render: (p) => ({
      headline: 'No contact method (phone, email, or form) could be found on your homepage.',
      impact: 'It is impossible for interested visitors to reach your business directly from this page.',
      fix: 'Add a phone number, contact form, or direct booking button immediately.',
      developer_brief: `Task: Add primary lead capture mechanism\nAction: Implement a working contact form or tap-to-call link in the header and hero.`,
      observed: p.observed || '0 phone links, 0 email links, 0 forms detected on landing page',
    }),
  },
};

export function instantiateFinding(
  code: string,
  params: Record<string, any> = {},
  evidence: any[] = [],
  confidence = 1.0,
  overrides: Partial<Finding> = {}
): Finding | null {
  const def = FINDING_CATALOG[code];
  if (!def) return null;

  const rendered = def.render(params);

  const headline = overrides.headline || rendered.headline;
  const impact = overrides.impact || rendered.impact;
  const fix = overrides.fix || rendered.fix;
  const developer_brief = overrides.developer_brief || rendered.developer_brief;

  const finding: Finding = {
    code: def.code,
    id: def.id,
    module: def.module,
    category: overrides.category || def.category || def.module,
    findingType: overrides.findingType || def.findingType || 'CONVERSION',
    severity: overrides.severity || def.severity,
    severityNum: overrides.severityNum || def.severityNum,
    effort: overrides.effort || def.effort,
    priority: overrides.priority || 0,
    priorityScore: overrides.priorityScore || 0,
    confidence: overrides.confidence !== undefined ? overrides.confidence : confidence,
    params,
    evidence: overrides.evidence || evidence,
    evidenceType: overrides.evidenceType || def.evidenceType || 'dom',
    source: overrides.source || def.source || 'BROWSER',

    headline,
    title: overrides.title || headline,
    impact,
    whyItMatters: overrides.whyItMatters || impact,
    fix,
    remediation: overrides.remediation || fix,
    developer_brief,
    developerBrief: overrides.developerBrief || developer_brief,

    observed: overrides.observed !== undefined ? overrides.observed : rendered.observed,
    heuristic: overrides.heuristic || def.heuristic,
    benchmark: overrides.benchmark || def.benchmark,
    inference: overrides.inference || rendered.inference,
    assumptions: overrides.assumptions || rendered.assumptions,
  };

  return finding;
}
